S02US04 Registration Form
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #117
Opened 2022-12-30 17:09 UTC by lucianpurcaru

2023-01-02 08:32 UTC, shvilaine submitted a review, later dismissed

2023-01-02 08:37 UTC, KevynSola commented on src/Entity/User.php
> +#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
Changer le message en Fr :)

2023-01-02 09:04 UTC, KevynSola submitted a review, later dismissed

2023-01-02 10:32 UTC, shvilaine approved these changes

2023-01-02 16:46 UTC, sblondeau requested changes

2023-01-02 16:46 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +    #[Route('/register', name: 'app_register')]
traduire l'url ?

2023-01-02 16:46 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            // do anything else you need here, like send an email
un petit message flash de success peut-etre ?

2023-01-02 16:46 UTC, sblondeau commented on src/Entity/User.php
>  class User implements UserInterface, PasswordAuthenticatedUserInterface
il manque quelques assert (length par ex) sur firstname, lastname, etc

2023-01-02 16:46 UTC, sblondeau commented on src/Entity/User.php
>  class User implements UserInterface, PasswordAuthenticatedUserInterface
vous avez vraiment besoin de garder username ou c'est l'emai qui sert d'identifiant ?

2023-01-02 16:46 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +            ])
sûr que c'est utile le username ?

2023-01-02 16:46 UTC, sblondeau commented on templates/login/index.html.twig
> +									<a href="/register" class="text-light-50 fw-bold text-decoration-none">Créez un !</a>
{{ path('app_register') }} et non "/register" en dur

2023-01-03 11:01 UTC, KevynSola commented on templates/base.html.twig
> +						{% for message in messages %}
Vérifier pourquoi ça ne fonctionne pas :(

2023-01-03 15:09 UTC, shvilaine approved these changes

2023-01-04 07:48 UTC, sblondeau approved these changes

2023-01-04 07:48 UTC, merged