S02US53 ads add on video page
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #122
Opened 2023-01-03 15:21 UTC by KevynSola

Closes #75 , Closes #76

2023-01-03 15:37 UTC, lucianpurcaru submitted a review, later dismissed

2023-01-03 21:06 UTC, shvilaine submitted a review, later dismissed

2023-01-04 07:57 UTC, sblondeau requested changes

2023-01-04 07:57 UTC, sblondeau commented on assets/styles/app.scss
> +@import "ads";
le fichier ads.scss est vide, à supprimer ? dans tous les cas il est plus à importer dans showvideo que dans le css global car tu ne mets pas des ads sur toutes les pages

2023-01-04 08:32 UTC, lucianpurcaru approved these changes

2023-01-04 08:38 UTC, sblondeau approved these changes

2023-01-04 08:38 UTC, merged