S02us57 add mention legal
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #143
Opened 2023-01-06 09:53 UTC by NefytZ

2023-01-06 10:17 UTC, sblondeau requested changes

2023-01-06 10:17 UTC, sblondeau commented on php.ini
>  upload_max_filesize=40M
pourquoi se fichier est touché ?

2023-01-06 10:17 UTC, sblondeau commented on src/Controller/HomeController.php
> +    #[Route('/legalnotices', name: 'app_legal')]
route en français

2023-01-06 10:17 UTC, sblondeau commented on templates/LegalNotices/index.html.twig
> +    <br>
pas de br en dehors d'un p

2023-01-06 10:22 UTC, NefytZ commented on php.ini
>  upload_max_filesize=40M
Aucune idée il est pas modifié pourtant

2023-01-06 10:22 UTC, NefytZ commented on src/Controller/HomeController.php
> +    #[Route('/legalnotices', name: 'app_legal')]
Oups

2023-01-06 10:23 UTC, NefytZ commented on templates/LegalNotices/index.html.twig
> +    <br>
C'est un copié collé d'un générateur de mentions légale c'est pas moi l'auteur du br😅

2023-01-06 10:28 UTC, Zakari-B commented on php.ini
>  upload_max_filesize=40M
Y'a pourtant deux lignes en trop qui ne se sont pas mises la toute seules. A retirer.

2023-01-06 16:26 UTC, sblondeau commented on php.ini
> +
pas corrigé, je ne veux plus voir ce fichier dans la PR

2023-01-06 16:26 UTC, sblondeau commented on src/Controller/HomeController.php
> +    #[Route('/mentionlegal', name: 'app_legal')]
pas corrigé

2023-01-09 08:53 UTC, sblondeau approved these changes

2023-01-09 08:53 UTC, merged