US02US03c - Admin redirection
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #145
Opened 2023-01-06 10:04 UTC by shvilaine

2023-01-06 10:10 UTC, lucianpurcaru submitted a review, later dismissed

2023-01-06 10:24 UTC, Zakari-B requested changes

2023-01-06 10:24 UTC, Zakari-B commented on src/Controller/LoginController.php
> +    #[Route('/redirect_admin', name: 'app_redirect_admin')]
C'est visible dans l'URL. Privilégie quelque chose de neutre comme juste "redirect" ou "index_redirect".

2023-01-06 10:24 UTC, Zakari-B commented on src/Controller/LoginController.php
> +        if ($roles[0] === ('ROLE_ADMIN')) {
A vérifier, mais il me semble que role[0] sera systématiquement ROLE_USER qui est attribué à tout le monde, admin inclus.

2023-01-06 10:28 UTC, sblondeau requested changes

2023-01-06 10:28 UTC, sblondeau commented on src/Controller/LoginController.php
> +            return $this->render('admin/index.html.twig', []);
non il ne faut pas faire ça, car tu n'es pas sûr que le role[0] soit ROLE_ADMIN
en plus ça ne prend pas en compte la hierarchie de ROLES...

2023-01-06 10:28 UTC, sblondeau commented on src/Controller/LoginController.php
> +            return $this->render('admin/index.html.twig', []);
mais au dela de ça, je pense que ça n'est pas très utile

2023-01-09 08:48 UTC, KevynSola approved these changes

2023-01-09 08:53 UTC, sblondeau approved these changes

2023-01-09 10:37 UTC, lucianpurcaru approved these changes

2023-01-09 11:22 UTC, merged