S03US11 crud videos create
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #175
Opened 2023-01-16 09:42 UTC by shvilaine

Close #148

2023-01-16 09:48 UTC, lucianpurcaru approved these changes

2023-01-16 10:19 UTC, sblondeau requested changes

2023-01-16 10:19 UTC, sblondeau commented on src/Form/VideoType.php
> +                        'maxSize' => '40m',
reste sur 2M, sinon ça va être pénible à gérer ;-)

2023-01-16 10:19 UTC, sblondeau commented on src/Entity/Video.php
> +        maxSize: '40M',
2M

2023-01-16 10:19 UTC, sblondeau commented on src/DataFixtures/VideoFixtures.php
> +                $video->setVideo($faker->imageUrl(640, 480, 'animals', true));
comme j'ai pu montrer en LC, j'aimerais que tu puisses avoir 2-3 vidéos fake
Le mieux serait d'avoir un dossier videos dans data fixtures, avec dedans video1.mp4, video2.mp4, video3.mp4...
et quand tu gères ton setVideo, plutot que de mettre un $faker->imageUrl, tu mets 'video'.rand(1,3)
et tu fais un copie de ton dossier video de data_fixtures vers uploads

je vous laisse regarder ça tous ensemble et on en discute si c'est pas clair
tu peux trouver des très courtes vidéo sur https://sample-videos.com/  par ex

2023-01-17 20:00 UTC, lucianpurcaru submitted a review, later dismissed

2023-01-18 08:43 UTC, sblondeau requested changes

2023-01-18 09:00 UTC, lucianpurcaru approved these changes

2023-01-18 10:03 UTC, sblondeau approved these changes

2023-01-18 10:03 UTC, merged