US33 Create a crud of ads
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #193
Opened 2023-01-18 10:31 UTC by KevynSola

Closes #176 , Closes #177

2023-01-18 10:33 UTC, lucianpurcaru approved these changes

2023-01-18 11:13 UTC, shvilaine submitted a review, later dismissed

2023-01-18 13:06 UTC, sblondeau requested changes
je ne comprends pas la US derrière ta PR
Ton US, c'est sensé être "Je peux créer une ads"
Mais là tu as fais ton CRUD en modifiant des choses par ci-par là pas rien de finalisé sur une des parties du CRUD (et selon la US ça devrait etre le Create là ?)

A finaliser

2023-01-18 13:52 UTC, KevynSola commented
> je ne comprends pas la US derrière ta PR Ton US, c'est sensé être "Je peux créer une ads" Mais là tu as fais ton CRUD en modifiant des choses par ci-par là pas rien de finalisé sur une des parties du CRUD (et selon la US ça devrait etre le Create là ?)
> 
> A finaliser

OK

2023-01-18 13:52 UTC, lucianpurcaru submitted a review, later dismissed

2023-01-18 14:07 UTC, shvilaine approved these changes

2023-01-19 08:13 UTC, sblondeau approved these changes

2023-01-19 08:13 UTC, merged