S03 US5 bloc video component
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #212
Opened 2023-01-19 16:16 UTC by KevynSola

Close #99

2023-01-19 16:17 UTC, lucianpurcaru approved these changes

2023-01-19 16:18 UTC, lucianpurcaru approved these changes

2023-01-19 16:55 UTC, sblondeau requested changes

2023-01-19 16:55 UTC, sblondeau commented on templates/components/_blocVideo.html.twig
> +			<img src="{{asset('build/images/LOCK.png')}}" alt="Connexion obligatoire" class="img-video-lock">
ça serait mieux de partir sur un SVG + text
il faut éviter de mettre un texte dans une image

2023-01-19 22:42 UTC, KevynSola commented on templates/components/_blocVideo.html.twig
> +			<img src="{{asset('build/images/LOCK.png')}}" alt="Connexion obligatoire" class="img-video-lock">
J'ai essayé mais vu que nous passons par le carrousel ça pose qq problème, donc j'ai simplifié...

2023-01-23 10:37 UTC, lucianpurcaru approved these changes

2023-01-23 11:07 UTC, shvilaine approved these changes

2023-01-23 11:57 UTC, sblondeau approved these changes

2023-01-23 11:57 UTC, merged