FIX - Slug filled automatically in Categories
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #213
Opened 2023-01-19 21:57 UTC by shvilaine

2023-01-19 22:43 UTC, KevynSola approved these changes

2023-01-20 08:31 UTC, lucianpurcaru approved these changes

2023-01-20 08:37 UTC, NefytZ submitted a review, later dismissed

2023-01-20 09:35 UTC, sblondeau requested changes

2023-01-20 09:35 UTC, sblondeau commented on src/Controller/AdminCatController.php
> +            $slug = $slugger->slug($category->getName());
j'ai l'impression que tu ajoutes un slug mais que tu ne l'utilises nul part ? dans la route qui affiche une category, faut bien uliser {slug} dans les param de route

2023-01-20 09:35 UTC, sblondeau commented on src/Controller/AdminCatController.php
>  #[Route('/admin/cat')]
admin/categorie

2023-01-20 09:35 UTC, sblondeau commented on src/Controller/AdminCatController.php
>      #[Route('/new', name: 'app_admin_cat_new', methods: ['GET', 'POST'])]
/ajouter

2023-01-20 10:02 UTC, lucianpurcaru approved these changes

2023-01-20 10:21 UTC, sblondeau approved these changes

2023-01-20 10:22 UTC, merged