Fix ads pics
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #252
Opened 2023-01-24 11:08 UTC by KevynSola

2023-01-24 11:09 UTC, lucianpurcaru submitted a review, later dismissed

2023-01-24 11:31 UTC, shvilaine submitted a review, later dismissed

2023-01-24 12:54 UTC, sblondeau requested changes
ce sont les images uploadées ? ça devrait etre dans un dossier upload non ? (ça peut se gérer aussi coté fixtures avec la fonction copy() si besoin, en stockant ces images dans data_fixtures comme pour les vidéos)

2023-01-24 19:09 UTC, lucianpurcaru approved these changes

2023-01-24 20:04 UTC, NefytZ approved these changes

2023-01-24 22:20 UTC, shvilaine approved these changes

2023-01-25 09:07 UTC, sblondeau approved these changes

2023-01-25 09:07 UTC, merged