S04US67 like videos
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #264
Opened 2023-01-25 13:46 UTC by lucianpurcaru

2023-01-25 14:14 UTC, lucianpurcaru commented
Close #265 #266 #267

2023-01-25 15:08 UTC, KevynSola approved these changes

2023-01-25 15:12 UTC, sblondeau requested changes

2023-01-25 15:12 UTC, sblondeau commented on migrations/Version20230125101806.php
> +        $this->addSql('ALTER TABLE favorites DROP FOREIGN KEY FK_8A048B9529C1004E');
problème dans ton make:mig, tu ne devais pas etre à jour sur ta bdd car ça drop favorites

2023-01-25 15:43 UTC, shvilaine approved these changes

2023-01-25 15:44 UTC, KevynSola approved these changes

2023-01-26 06:54 UTC, sblondeau approved these changes

2023-01-26 06:57 UTC, merged