Fix view on sponsor's placeholder
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #271
Opened 2023-01-25 15:22 UTC by lucianpurcaru

2023-01-25 15:32 UTC, KevynSola requested changes

2023-01-25 15:32 UTC, KevynSola commented on migrations/Version20230125151242.php
> +        $this->addSql('ALTER TABLE user_video_likes DROP FOREIGN KEY FK_6FB38E4A29C1004E');
Tu te retrouve avec la table user_video_likes alors que tu es dans le fix sponsor... :(

2023-01-25 15:42 UTC, shvilaine approved these changes

2023-01-25 15:42 UTC, KevynSola approved these changes

2023-01-26 07:01 UTC, sblondeau approved these changes

2023-01-26 07:01 UTC, merged