Fix preview premium on carrousel and hover lock to login
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #348
Opened 2023-01-29 20:33 UTC by KevynSola

Close #332

2023-01-29 21:32 UTC, lucianpurcaru approved these changes

2023-01-29 22:32 UTC, sblondeau requested changes

2023-01-29 22:32 UTC, sblondeau commented on templates/components/_thumbnailPremium.html.twig
> +		<img src={{ asset('build/images/videoPlaceholder.jpeg') }} alt="{{video.name}}" class="img-video-lock">
tu peux mettre le if uniquement autour de l'img, le reste étant répété et identique entre le if et le else

2023-01-29 23:54 UTC, KevynSola commented on templates/components/_thumbnailPremium.html.twig
> +		<img src={{ asset('build/images/videoPlaceholder.jpeg') }} alt="{{video.name}}" class="img-video-lock">
Ah oui en effet, j'avais même pas remarqué.

2023-01-30 09:58 UTC, lucianpurcaru approved these changes

2023-01-30 12:07 UTC, sblondeau approved these changes

2023-01-30 12:07 UTC, merged