FIX sponsors size and added filter
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #413
Opened 2023-01-31 14:22 UTC by lucianpurcaru

2023-01-31 14:42 UTC, shvilaine submitted a review, later dismissed

2023-01-31 15:21 UTC, sblondeau requested changes

2023-01-31 15:21 UTC, sblondeau commented on templates/components/_sponsor.html.twig
> +				<div class="col-3">
col-md-3 et col-sm-6 ou qq chose comme ça, pas de media query

2023-01-31 15:21 UTC, sblondeau commented on assets/styles/_sponsor.scss
> +@media (max-width:1000px) {
non gérer avec bootstrap

2023-02-06 08:13 UTC, KevynSola approved these changes

2023-02-06 08:14 UTC, shvilaine approved these changes

2023-02-06 08:44 UTC, merged

2023-02-06 13:26 UTC, lucianpurcaru commented
Close #354