Fix resize and condition when empty
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #451
Opened 2023-02-06 21:57 UTC by KevynSola

Closes #448 , #449 , #450

2023-02-06 22:11 UTC, lucianpurcaru approved these changes

2023-02-07 08:01 UTC, sblondeau requested changes

2023-02-07 08:01 UTC, sblondeau commented on src/Controller/VideoController.php
> +        if ($ads != null) {
!==

2023-02-07 08:01 UTC, sblondeau commented on templates/video/index.html.twig
> +			{% if ads != null %}
if ads is not null

2023-02-07 13:55 UTC, shvilaine approved these changes

2023-02-07 13:58 UTC, sblondeau approved these changes

2023-02-07 13:58 UTC, merged