Fix flash message component
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #458
Opened 2023-02-06 23:03 UTC by KevynSola

Close #434

2023-02-06 23:04 UTC, lucianpurcaru approved these changes

2023-02-07 08:25 UTC, sblondeau requested changes

2023-02-07 08:25 UTC, sblondeau commented on src/Controller/AdController.php
> +            $this->addFlash('success', 'La publicité à bien été modifié.');
ée

2023-02-07 08:25 UTC, sblondeau commented on src/Controller/AdController.php
> +            $this->addFlash('success', 'La publicité à bien été modifié.');
à corriger sur tous les messages en dessous

2023-02-07 08:27 UTC, Zakari-B requested changes

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/ActualityController.php
> +            $this->addFlash('success', 'La bannière à bien été modifié.');
a / modifiée.

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdController.php
> +            $this->addFlash('success', 'La publicité à bien été ajouté.');
a / ajoutée.

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdController.php
> +            $this->addFlash('success', 'La publicité à bien été modifié.');
a / modifiée.

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdminCatController.php
> +            $this->addFlash('success', 'La catégorie à bien été modifié.');
a / modifiée.

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdminSponsorController.php
> +            $this->addFlash('success', 'Le sponsor à bien été modifié.');
a

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdminVideoController.php
> +            $this->addFlash('success', 'La vidéo à bien été modifié.');
a / modifiée.

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/AdminVideoController.php
> +            $this->addFlash('success', 'La vidéo à bien été supprimée.');
a

2023-02-07 08:27 UTC, Zakari-B commented on src/Controller/ActualityController.php
> +            $this->addFlash('success', 'La bannière à bien été supprimée.');
a

2023-02-07 13:59 UTC, lucianpurcaru approved these changes

2023-02-07 14:06 UTC, merged