S01US45 Création du footer#57
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #61
Opened 2022-12-14 10:26 UTC by lucianpurcaru

2022-12-14 10:39 UTC, KevynSola approved these changes

2022-12-14 13:09 UTC, shvilaine submitted a review, later dismissed

2022-12-14 14:04 UTC, sblondeau requested changes

2022-12-14 14:04 UTC, sblondeau commented on templates/components/_footer.html.twig
> +				<div class="col-md-3 col-lg-3 mx-auto my-4 text-center">
pas de mx sur des col

2022-12-14 14:04 UTC, sblondeau commented on templates/components/_footer.html.twig
> +	<div class="container p-4 pb-0">
pas de px- sur des container

2022-12-14 14:04 UTC, sblondeau commented on templates/components/_footer.html.twig
> +		<section class="">
plutot ici le p-4

2022-12-15 08:28 UTC, sblondeau approved these changes

2022-12-15 08:28 UTC, merged