S01US31 creation categories
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #73
Opened 2022-12-15 11:41 UTC by shvilaine

2022-12-15 13:15 UTC, lucianpurcaru submitted a review, later dismissed

2022-12-15 14:31 UTC, KevynSola submitted a review, later dismissed

2022-12-15 14:42 UTC, Zakari-B commented on src/DataFixtures/CategoryFixtures.php
> +    public const CATEGORIES = [
Pas d'espace dans ces catégories puisqu'elles sont utilisées dans le addReference.

2022-12-15 14:43 UTC, Zakari-B requested changes

2022-12-15 14:43 UTC, Zakari-B commented on src/DataFixtures/CategoryFixtures.php
> +    public const CATEGORIES = [
Pas d'espace dans ces catégories puisqu'elles sont utilisées dans le addReference.

2022-12-15 15:48 UTC, KevynSola submitted a review, later dismissed

2022-12-16 08:27 UTC, sblondeau requested changes

2022-12-16 08:27 UTC, sblondeau commented on src/Entity/Category.php
> +    #[Assert\Length(max: 255, maxMessage:'Catégorie saisie {{ value }} trop longue ({{ limit }} caractères maximum)')]
ne t'amuses pas à écrire tes propres messages d'erreur, ceux par défaut sont très bien. assure toi juste d'avoir mis la langue en fr dans config/package/translation.yaml

2022-12-16 08:27 UTC, sblondeau commented on assets/styles/app.scss
> +@import "categories";
le style categories et showvideo ne s'appliquent pas à toutes les pages, 
or là tu les importe dans app.scss donc elle vont se retrouver dans app.css et donc sur toutes les pages
Il faut que tu génères un nouveau fichier  categories.css et showVideo.css que tu importera uniquement dans les pages concernées

ça se fait dans le webpack.config via un addStyleEntry. 
https://symfony.com/doc/current/frontend/encore/simple-example.html#compiling-only-a-css-file

Si ce n'est pas clair, voit avec tes collègues d'externatic par ex, je leur ai fait faire hier

2022-12-16 09:04 UTC, shvilaine commented on assets/styles/app.scss
> +@import "categories";
OK, vu avec team Externatic.

2022-12-16 09:15 UTC, shvilaine commented on src/Entity/Category.php
> +    #[Assert\Length(max: 255, maxMessage:'Catégorie saisie {{ value }} trop longue ({{ limit }} caractères maximum)')]
Assertions supprimées pour le moment. fichier translation.yaml modifié pour langue:fr

2022-12-16 09:18 UTC, KevynSola approved these changes

2022-12-16 09:18 UTC, lucianpurcaru approved these changes

2022-12-16 10:14 UTC, sblondeau approved these changes

2022-12-16 10:14 UTC, merged