S01US30 Page d'accueil
WildCodeSchool/202209-orleans-php-project-originsdigital pull request #80
Opened 2022-12-15 18:35 UTC by KevynSola

2022-12-15 18:46 UTC, lucianpurcaru submitted a review, later dismissed

2022-12-15 21:38 UTC, shvilaine approved these changes

2022-12-16 08:29 UTC, sblondeau requested changes

2022-12-16 08:29 UTC, sblondeau commented on assets/styles/app.scss
> +@import "home";
meme retour qu'à Hélène sur l'import de css

2022-12-16 09:19 UTC, lucianpurcaru submitted a review, later dismissed

2022-12-16 09:58 UTC, shvilaine approved these changes

2022-12-16 10:11 UTC, shvilaine approved these changes

2022-12-16 10:15 UTC, sblondeau submitted a review, later dismissed

2022-12-16 10:29 UTC, lucianpurcaru approved these changes

2022-12-16 10:36 UTC, merged